# Generated by Django 5.0.1 on 2024-03-26 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouriteitem',
            name='quantity',
        ),
    ]
